### ISSUE TITLE
PDBF compiler is currently broken for Linux and Mac

### ISSUE THREAD

**Issue by IchbinkeinReh** [uds-datalab/PDBF#23]

**Comment by jensdittrich** [comment]
Hallo Herr Bender,

was ist eigentlich der Stand?

Wieso ist der Compiler kaputt? Ich nehme an, dass das Release funktioniert?

Wie hat eigentlich die Interaktion mit Stefan geklappt?

Grüße
jd


Am 01.11.2015 um 10:42 schrieb Patrick Bender <notifications@github.com>:

> —
> Reply to this email directly or view it on GitHub.
> 

--
Jens Dittrich
Full Professor, Computer Science, Saarland University
E1 1, 3.11, +49 (0)681 302 70140
infosys.uni-saarland.de / datenbankenlernen.de

**Comment by IchbinkeinReh** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Hallo,
Nein das release löst dieses problem leider nicht. Für Mac und Linux schein der compiler schon seit version 1.0 kaputt zu sein. Ist nur nie aufgefallen bis ich mal die tests auch auf linux und mac laufen lassen habe. Dieses release löst nur andere probleme die während der zusammenarbeit mit stefan aufgetreten sind. Da meine stunden für diese woche schon aufgebraucht sind werde ich mich am nächsten montag damit beschäftigen. Stefan hat das paper jetzt ohne PDBF eingereicht.
Gruß
Patrick

On November 2, 2015 1:18:36 PM CET, jensdittrich <notifications@github.com> wrote:
>Hallo Herr Bender,
>
>was ist eigentlich der Stand?
>
>Wieso ist der Compiler kaputt? Ich nehme an, dass das Release
>funktioniert?
>
>Wie hat eigentlich die Interaktion mit Stefan geklappt?
>
>Grüße
>jd
>
>
>Am 01.11.2015 um 10:42 schrieb Patrick Bender
><notifications@github.com>:
>
>> —
>> Reply to this email directly or view it on GitHub.
>>
>
>--
>Jens Dittrich
>Full Professor, Computer Science, Saarland University
>E1 1, 3.11, +49 (0)681 302 70140
>infosys.uni-saarland.de / datenbankenlernen.de
>
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/uds-datalab/PDBF/issues/23#issuecomment-153001236
-----BEGIN PGP SIGNATURE-----
Version: APG v1.1.1

iQFIBAEBCgAyBQJWN2E0KxxQYXRyaWNrIEJlbmRlciA8aWNoYmlua2VpbnJlaEB0
LW9ubGluZS5kZT4ACgkQGswa4HlPuuTyEAf+KXXxaHwRKsD4JeSkqsIf01JJnTcU
sNfunonvxRwVfo8KCyx+W9sggEuYTDrRdDXoqpdokahn8n1SxoY/MnxyameIJ4MI
WgbGcRrXz3+bxPy7xDn4btu4XjwYgD7n12Q8GMGiZjbEe7+yzKuwfWI/VMIj42Qq
mf/HjFlw7UJNNYXjz2nEC8twyd0FwsaqWcpXy8gvt6DqIVd03ZjAxNSlCAsIobPt
5rqpYRlLnKSnU96l68TsrlMNrYm1N+H0C24IqrChd4ZwaX4poaoBTLTeClhXuvju
HrfculfGDKrY5hZJ05LCqwCOn9NIy26kEHXp+xEMJ8j1VDSdyxUUk3mgkQ==
=SsEq
-----END PGP SIGNATURE-----
